export const shop = {
  name: 'Daily Drivin',
  legalName: 'Daily Drivin',
  person: 'Joe',
  city: 'Hillsboro',
  state: 'TX',
  locationLabel: 'Hillsboro, Texas',
  serviceArea: 'Hillsboro, TX and about a 30-mile radius',
  serviceAreaShort: 'Hillsboro + 30 miles',
  phoneDisplay: '(682) 202-5058',
  phoneTel: '+16822025058',
  smsUrl: 'sms:+16822025058',
  telUrl: 'tel:+16822025058',
  email: null,
  emailNote: 'Email coming soon.',
  instagramHandle: null,
  instagramNote: 'Instagram coming.',
  tagline: 'Mobile auto care. Joe comes to you.',
  lede: 'Cars and trucks around Hillsboro, Texas and about thirty miles out.',
  hoursHeadline: 'By appointment',
  hoursBody:
    'No fixed shop hours. Joe posts weekly appointment windows, and they change. Same-day is sometimes possible.',
  payment: 'Cash or card',
  noEmergencyNote: 'Text is preferred. There is no after-hours or emergency line.',
  checkoverNote: 'An initial check-over is typically 1–2 hours.',
  bookingWindowNote: 'Request a time up to about two months out.',
  bookingPendingNote: 'A request is pending until Joe confirms. It is not a guaranteed lock.',
  exclusionsNote: 'Ask if you are unsure — Joe will say if it is a fit.',
  rewardsNote:
    'Sign up for discounts and rewards. The exact offer is still being set — no points formula yet.',
  bio: [
    'Joe has eight years in automotive: four years in a service department as a technician, and four years in an auto care shop doing engine maintenance and suspension.',
    'Daily Drivin is his mobile shop. He comes to you in the Hillsboro, Texas area and about thirty miles out — cars and trucks, fluids, suspension, engine work, and a quality check-over.',
  ],
  workList: [
    'Mobile service for cars and trucks',
    'Fluids, engine, and suspension',
    'Quality check-over / inspection-style visits',
    'Ask if you are unsure — Joe will tell you if it is a fit',
  ],
};
